apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mbch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mbch
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mbch
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mbch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mbch
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epnq-tenant/rhtap-demo-app/hacbs-test-project-mbch@sha256:f746f375bd2481f54f4949a5bb4e80ce10cc7cea013b8f738353baba53b65176
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
