apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mbch
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epnq-tenant/rhtap-demo-app/hacbs-test-project-mbch@sha256:304289390646c80797184c9929c259c1766503dc3d85be6a04330b4c9dc1ce09
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
